# Generated by Django 6.1.2 on 2026-10-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('create_voucher', 'Puede crear vales de salida'), ('authorize_voucher', 'Puede autorizar vales de salida'), ('cancel_voucher', 'Puede cancelar vales y líneas de vale'), ('dispatch_voucher', 'Puede surtir vales con número de serie'), ('cancel_dispatched_item', 'Puede cancelar piezas surtidas (dentro de 120h)'), ('register_return', 'Puede registrar devolución de equipo desde centro'), ('confirm_return', 'Puede confirmar devolución y emitir dictamen de almacén'), ('assign_repair_folio', 'Puede asignar folio de reparación de oficina'), ('assign_engineer', 'Puede asignar ingeniero para reparación'), ('define_equipment', 'Puede definir equipo técnico (reparado/huesario/garantía)'), ('review_definition_boss', 'Puede confirmar o rechazar definición técnica (Jefe)'), ('review_definition_warehouse', 'Puede confirmar definición técnica en almacén'), ('manage_scrap', 'Puede gestionar flujo de entrega a huesario/scrap'), ('manage_workshop', 'Puede gestionar traslados a taller habilitado'), ('assign_workshop_repair', 'Puede asignar reparación dentro de taller'), ('define_workshop_equipment', 'Puede dictaminar y definir equipo en taller'), ('view_coupa_consumption', 'Puede consultar y registrar consumos Coupa'), ('register_return_without_dispatch', 'Puede registrar devolución sin salida previa'), ('view_zone_reports', 'Puede consultar bitácoras y reportes a nivel zona'), ('export_reports', 'Puede exportar reportes y kárdex a formato Excel/XLSX'), ('view_case', 'Puede consultar casos de devolución')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
