# Generated by Django 6.1.2 on 2026-10-07 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0001_initial'),
        ('org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True, verbose_name='ID de AppSheet original')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('origin_type', models.CharField(choices=[('VALE', 'Vale Estándar'), ('COUPA', 'Consumo Coupa')], default='VALE', max_length=20, verbose_name='Tipo de origen')),
                ('coupa_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='ID de Coupa')),
                ('report_folio', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Folio de reporte / ticket')),
                ('shipping_type', models.CharField(choices=[('FISICO', 'Físico / Entrega en mano'), ('PAQUETERIA_EXTERNA', 'Paquetería Externa'), ('DISTRIBUCION', 'Distribución Interna')], default='FISICO', max_length=32, verbose_name='Tipo de envío')),
                ('project_name', models.CharField(blank=True, default='', max_length=128, verbose_name='Nombre de proyecto')),
                ('status', models.CharField(choices=[('PENDIENTE_SURTIDO', 'Pendiente de Surtido'), ('SURTIDO', 'Surtido'), ('CANCELADO', 'Cancelado')], db_index=True, default='PENDIENTE_SURTIDO', max_length=32, verbose_name='Estatus')),
                ('authorized_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de autorización')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega / surtido')),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/vouchers/%Y/%m/', verbose_name='Firma de recepción')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='docs/vouchers/%Y/%m/', verbose_name='PDF de vale de salida')),
                ('comments', models.TextField(blank=True, default='', verbose_name='Comentarios')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cancelación')),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authorized_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='Autorizado por')),
                ('cancel_reason', models.ForeignKey(blank=True, limit_choices_to={'catalog': 'VOUCHER_CANCEL_REASON'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_vouchers_by_reason', to='catalog.catalogvalue', verbose_name='Motivo de cancelación')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='Cancelado por')),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivered_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='Entregado por (Almacén)')),
                ('destination_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='org.center', verbose_name='Centro destino')),
                ('material_category', models.ForeignKey(blank=True, limit_choices_to={'catalog': 'MATERIAL_CATEGORY'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vouchers_by_category', to='catalog.catalogvalue', verbose_name='Categoría de material')),
                ('reason', models.ForeignKey(blank=True, limit_choices_to={'catalog': 'REQUEST_REASON'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vouchers_by_reason', to='catalog.catalogvalue', verbose_name='Motivo de solicitud')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='Recibido por')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='org.region', verbose_name='Región')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
            ],
            options={
                'verbose_name': 'Vale',
                'verbose_name_plural': 'Vales',
                'db_table': 'vouchers_voucher',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True, verbose_name='ID de AppSheet original')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('requested_text', models.CharField(blank=True, default='', max_length=255, verbose_name='Descripción solicitada (texto libre)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad solicitada')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('SURTIDO', 'Surtido'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estatus')),
                ('comments', models.TextField(blank=True, default='', verbose_name='Comentarios')),
                ('cancel_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_lines', to='catalog.catalogvalue', verbose_name='Motivo de cancelación')),
                ('equipment_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voucher_lines', to='inventory.equipmentmodel', verbose_name='Modelo de equipo')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='vouchers.voucher', verbose_name='Vale')),
            ],
            options={
                'verbose_name': 'Línea de vale',
                'verbose_name_plural': 'Líneas de vale',
                'db_table': 'vouchers_line',
            },
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['region', 'status'], name='vouchers_vo_region__16e4e3_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['report_folio'], name='vouchers_vo_report__a12230_idx'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('origin_type', 'VALE'), ('coupa_id__isnull', True)), models.Q(('origin_type', 'COUPA'), ('coupa_id__isnull', False)), _connector='OR'), name='check_voucher_origin_coupa_integrity'),
        ),
    ]
