# Generated by Django 6.1.2 on 2026-10-07 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True, verbose_name='ID de AppSheet original')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('location', models.CharField(choices=[('CENTRO', 'Centro / En Campo'), ('TALLER', 'Taller Habilitado')], default='CENTRO', max_length=20, verbose_name='Ubicación operativa')),
                ('route', models.CharField(choices=[('EVALUACION_CENTRO', 'Evaluación en Centro'), ('TALLER_HABILITADO', 'Taller Habilitado'), ('STOCK_DIRECTO', 'Stock Directo')], default='EVALUACION_CENTRO', max_length=32, verbose_name='Ruta de atención')),
                ('applies_workshop_entry', models.BooleanField(default=False, verbose_name='¿Aplica entrada a taller?')),
                ('returned_brand', models.CharField(blank=True, default='', max_length=128, verbose_name='Marca')),
                ('returned_model_text', models.CharField(blank=True, default='', max_length=128, verbose_name='Modelo devuelto (texto)')),
                ('returned_serial', models.CharField(db_index=True, max_length=128, verbose_name='Número de serie devuelto')),
                ('shipping_type', models.CharField(choices=[('FISICO', 'Físico'), ('DISTRIBUCION', 'Distribución')], default='FISICO', max_length=32, verbose_name='Tipo de envío')),
                ('shipping_folio', models.CharField(blank=True, default='', max_length=64, verbose_name='Folio de envío (EM o SA)')),
                ('return_status', models.CharField(blank=True, default='PENDIENTE_CONFIRMAR', max_length=64, verbose_name='Estatus de devolución')),
                ('failure', models.TextField(blank=True, default='', verbose_name='Descripción de la falla')),
                ('return_pdf', models.FileField(blank=True, null=True, upload_to='docs/returns/%Y/%m/', verbose_name='PDF de regreso')),
                ('return_qr', models.ImageField(blank=True, null=True, upload_to='qr/returns/%Y/%m/', verbose_name='QR de regreso')),
                ('repair_folio', models.CharField(blank=True, default='', max_length=64, verbose_name='Folio de reparación')),
                ('folio_date', models.DateField(blank=True, null=True, verbose_name='Fecha de folio')),
                ('attention_folio', models.CharField(blank=True, default='', max_length=64, verbose_name='Folio de atención')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de asignación')),
                ('definition', models.CharField(blank=True, choices=[('REPARADO', 'Reparado'), ('HUESARIO', 'Huesario / Scrap'), ('GARANTIA', 'Garantía')], max_length=32, null=True, verbose_name='Definición técnica')),
                ('repair_comments', models.TextField(blank=True, default='', verbose_name='Comentarios de reparación')),
                ('repaired_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de reparación/definición')),
                ('insight_repair_confirmed', models.BooleanField(default=False, verbose_name='Insight reparación confirmado')),
                ('insight_entry_confirmed', models.BooleanField(default=False, verbose_name='Insight entrada confirmado')),
                ('destination_warehouse', models.CharField(blank=True, default='STOCK', max_length=32, verbose_name='Almacén destino')),
                ('warranty_solution', models.CharField(blank=True, choices=[('NUEVO', 'Nuevo'), ('RECUPERADO', 'Recuperado')], max_length=32, null=True, verbose_name='Solución de garantía')),
                ('new_serial', models.CharField(blank=True, default='', max_length=128, verbose_name='Nueva serie (garantía nuevo)')),
                ('review_reason', models.TextField(blank=True, default='', verbose_name='Motivo de revisión')),
                ('scrap_status', models.CharField(blank=True, choices=[('CONFIRMADO', 'Confirmado para Huesario'), ('ENVIADO', 'Enviado a Huesario')], max_length=32, null=True, verbose_name='Estatus de huesario')),
                ('stage', models.CharField(db_index=True, default='PENDIENTE_CONFIRMAR', max_length=64, verbose_name='Etapa actual del caso')),
                ('applies_reason', models.ForeignKey(blank=True, limit_choices_to={'catalog': 'APPLIES_REASON'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='case_applies_reasons', to='catalog.catalogvalue', verbose_name='Motivo por el que aplica a taller')),
                ('assigned_engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_cases', to=settings.AUTH_USER_MODEL, verbose_name='Ingeniero asignado')),
                ('insight_entry_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entry_insight_notes', to='catalog.catalogvalue', verbose_name='Nota Insight entrada')),
                ('insight_repair_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='repair_insight_notes', to='catalog.catalogvalue', verbose_name='Nota Insight reparación')),
            ],
            options={
                'verbose_name': 'Caso de equipo',
                'verbose_name_plural': 'Casos de equipo',
                'db_table': 'cases_equipment_case',
                'ordering': ['-created_at'],
            },
        ),
    ]
