# Generated by Django 6.1.2 on 2026-10-07 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('catalog', '0001_initial'),
        ('inventory', '0001_initial'),
        ('org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentcase',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='inventory.inventoryitem', verbose_name='Pieza surtida original'),
        ),
        migrations.AddField(
            model_name='equipmentcase',
            name='origin_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_cases', to='org.region', verbose_name='Región de origen'),
        ),
        migrations.AddField(
            model_name='equipmentcase',
            name='predefinition',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalog': 'PREDEFINITION'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='case_predefinitions', to='catalog.catalogvalue', verbose_name='Predefinición de falla'),
        ),
        migrations.AddField(
            model_name='equipmentcase',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_cases', to=settings.AUTH_USER_MODEL, verbose_name='Recibido en almacén por'),
        ),
        migrations.AddField(
            model_name='equipmentcase',
            name='returned_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='case_returns', to='inventory.equipmentmodel', verbose_name='Modelo identificado'),
        ),
        migrations.AddField(
            model_name='equipmentcase',
            name='ruling',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalog': 'RULING'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='case_rulings', to='catalog.catalogvalue', verbose_name='Dictamen de almacén'),
        ),
        migrations.AddField(
            model_name='equipmentcase',
            name='stock_direct_reason',
            field=models.ForeignKey(blank=True, limit_choices_to={'catalog': 'STOCK_DIRECT_REASON'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='case_stock_direct_reasons', to='catalog.catalogvalue', verbose_name='Motivo de stock directo'),
        ),
        migrations.AddField(
            model_name='equipmentcase',
            name='workshop_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workshop_cases', to='org.region', verbose_name='Región de taller asignado'),
        ),
        migrations.AddIndex(
            model_name='equipmentcase',
            index=models.Index(fields=['origin_region', 'stage'], name='cases_equip_origin__977e00_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentcase',
            index=models.Index(fields=['returned_serial'], name='cases_equip_returne_1cfd5e_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentcase',
            index=models.Index(fields=['location', 'stage'], name='cases_equip_locatio_48faba_idx'),
        ),
    ]
