# Generated by Django 6.1.2 on 2026-10-07 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(db_index=True, max_length=64, verbose_name='Tipo de entidad')),
                ('entity_id', models.BigIntegerField(db_index=True, verbose_name='ID de entidad')),
                ('action_code', models.CharField(db_index=True, max_length=64, verbose_name='Código de acción')),
                ('from_stage', models.CharField(blank=True, default='', max_length=64, verbose_name='Etapa anterior')),
                ('to_stage', models.CharField(blank=True, default='', max_length=64, verbose_name='Etapa nueva')),
                ('outcome', models.CharField(choices=[('CONFIRMADO', 'Confirmado'), ('RECHAZADO', 'Rechazado'), ('NA', 'No Aplica')], default='NA', max_length=20, verbose_name='Resultado')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comentarios')),
                ('reason_code', models.CharField(blank=True, default='', max_length=64, verbose_name='Código de motivo')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Datos complementarios')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y hora')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='core_events', to=settings.AUTH_USER_MODEL, verbose_name='Usuario ejecutor')),
            ],
            options={
                'verbose_name': 'Evento de auditoría',
                'verbose_name_plural': 'Eventos de auditoría',
                'db_table': 'core_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='core_event_entity__f1011a_idx'), models.Index(fields=['action_code', 'created_at'], name='core_event_action__4af032_idx')],
            },
        ),
    ]
