"""Declarative registry of business transitions for SSIT 2.0.

Each transition defines:
- code: Unique action identifier
- entity: Target model (VOUCHER, LINE, ITEM, CASE)
- label: Human-readable action label in Spanish
- from_stages: List of valid source stages
- to_stage: Resulting target stage
- permission: Required permission codename
- scope_rule: Scope filter rule (REGION, ZONE, OWN, ASSIGNED, GLOBAL)
- inputs_schema: Expected input fields specification
- conditions: Validation conditions
- kardex_effect: NONE, SALIDA, ENTRADA
- is_bulk: Whether the transition supports batch operations
"""
from typing import Any

TRANSITIONS_REGISTRY: dict[str, dict[str, Any]] = {
    # =========================================================================
    # 1. VALES Y SURTIDO
    # =========================================================================
    "create_voucher": {
        "code": "create_voucher",
        "entity": "VOUCHER",
        "label": "Crear Vale de Salida",
        "from_stages": [""],
        "to_stage": "PENDIENTE_SURTIDO",
        "permission": "create_voucher",
        "scope_rule": "REGION",
        "inputs_schema": {
            "destination_center_id": {"type": "integer", "required": True},
            "reason_id": {"type": "integer", "required": True},
            "material_category_id": {"type": "integer", "required": False},
            "shipping_type": {"type": "string", "required": True},
            "report_folio": {"type": "string", "required": False},
            "comments": {"type": "string", "required": False},
            "lines": {"type": "list", "required": True},
        },
        "conditions": {},
        "kardex_effect": "NONE",
        "is_bulk": False,
    },
    "authorize_voucher": {
        "code": "authorize_voucher",
        "entity": "VOUCHER",
        "label": "Autorizar Vale",
        "from_stages": ["PENDIENTE_SURTIDO"],
        "to_stage": "PENDIENTE_SURTIDO",  # Permanece pendiente pero con authorized_at marcado
        "permission": "authorize_voucher",
        "scope_rule": "REGION",
        "inputs_schema": {
            "comments": {"type": "string", "required": False},
        },
        "conditions": {
            "must_not_be_authorized": True,
        },
        "kardex_effect": "NONE",
        "is_bulk": True,
    },
    "cancel_voucher": {
        "code": "cancel_voucher",
        "entity": "VOUCHER",
        "label": "Cancelar Vale",
        "from_stages": ["PENDIENTE_SURTIDO"],
        "to_stage": "CANCELADO",
        "permission": "cancel_voucher",
        "scope_rule": "REGION",
        "inputs_schema": {
            "cancel_reason_id": {"type": "integer", "required": True},
            "comments": {"type": "string", "required": False},
        },
        "conditions": {},
        "kardex_effect": "NONE",
        "is_bulk": False,
    },
    "cancel_line": {
        "code": "cancel_line",
        "entity": "LINE",
        "label": "Cancelar Línea de Vale",
        "from_stages": ["PENDIENTE"],
        "to_stage": "CANCELADO",
        "permission": "cancel_voucher",
        "scope_rule": "REGION",
        "inputs_schema": {
            "cancel_reason_id": {"type": "integer", "required": True},
            "comments": {"type": "string", "required": False},
        },
        "conditions": {},
        "kardex_effect": "NONE",
        "is_bulk": False,
    },
    "dispatch_voucher": {
        "code": "dispatch_voucher",
        "entity": "VOUCHER",
        "label": "Surtir Vale con Series",
        "from_stages": ["PENDIENTE_SURTIDO"],
        "to_stage": "SURTIDO",
        "permission": "dispatch_voucher",
        "scope_rule": "REGION",
        "inputs_schema": {
            "received_by_id": {"type": "integer", "required": True},
            "items_data": {"type": "list", "required": True},  # List of {line_id, model_id, serial_number, condition, warehouse}
            "signature_data": {"type": "string", "required": False},
            "comments": {"type": "string", "required": False},
        },
        "conditions": {
            "require_authorization": True,
        },
        "kardex_effect": "SALIDA",
        "is_bulk": False,
    },
    "register_coupa_consumption": {
        "code": "register_coupa_consumption",
        "entity": "VOUCHER",
        "label": "Registrar Consumo Coupa",
        "from_stages": [""],
        "to_stage": "SURTIDO",
        "permission": "view_coupa_consumption",
        "scope_rule": "GLOBAL",
        "inputs_schema": {
            "coupa_id": {"type": "string", "required": True},
            "destination_center_id": {"type": "integer", "required": True},
            "items_data": {"type": "list", "required": True},
            "comments": {"type": "string", "required": False},
        },
        "conditions": {},
        "kardex_effect": "SALIDA",
        "is_bulk": False,
    },
    "cancel_dispatched_item": {
        "code": "cancel_dispatched_item",
        "entity": "ITEM",
        "label": "Cancelar Pieza Surtida",
        "from_stages": [""],
        "to_stage": "CANCELADO",
        "permission": "cancel_dispatched_item",
        "scope_rule": "REGION",
        "inputs_schema": {
            "cancel_note": {"type": "string", "required": True},
        },
        "conditions": {
            "max_hours_limit": 120,  # Máximo 120 horas desde surtido
            "must_not_have_return_case": True,
        },
        "kardex_effect": "ENTRADA",
        "is_bulk": False,
    },

    # =========================================================================
    # 2. DEVOLUCIONES, DICTAMEN Y REPARACIÓN
    # =========================================================================
    "register_return": {
        "code": "register_return",
        "entity": "CASE",
        "label": "Registrar Devolución en Centro",
        "from_stages": [""],
        "to_stage": "PENDIENTE_CONFIRMAR",
        "permission": "register_return",
        "scope_rule": "REGION",
        "inputs_schema": {
            "item_id": {"type": "integer", "required": False},
            "returned_model_id": {"type": "integer", "required": True},
            "returned_serial": {"type": "string", "required": True},
            "returned_brand": {"type": "string", "required": False},
            "route": {"type": "string", "required": True},
            "shipping_type": {"type": "string", "required": True},
            "shipping_folio": {"type": "string", "required": False},
            "failure": {"type": "string", "required": False},
            "applies_workshop_entry": {"type": "boolean", "required": False},
            "applies_reason_id": {"type": "integer", "required": False},
            "insight_confirmed": {"type": "boolean", "required": False},
        },
        "conditions": {},
        "kardex_effect": "NONE",
        "is_bulk": False,
    },
    "register_return_without_dispatch": {
        "code": "register_return_without_dispatch",
        "entity": "CASE",
        "label": "Registrar Devolución sin Salida Previa",
        "from_stages": [""],
        "to_stage": "PENDIENTE_CONFIRMAR",
        "permission": "register_return_without_dispatch",
        "scope_rule": "REGION",
        "inputs_schema": {
            "returned_model_id": {"type": "integer", "required": True},
            "returned_serial": {"type": "string", "required": True},
            "returned_brand": {"type": "string", "required": False},
            "route": {"type": "string", "required": True},
            "shipping_type": {"type": "string", "required": True},
            "failure": {"type": "string", "required": False},
        },
        "conditions": {},
        "kardex_effect": "NONE",
        "is_bulk": False,
    },
    "confirm_return": {
        "code": "confirm_return",
        "entity": "CASE",
        "label": "Confirmar Devolución y Dictaminar (Almacén)",
        "from_stages": ["PENDIENTE_CONFIRMAR"],
        "to_stage": "CONFIRMADO",
        "permission": "confirm_return",
        "scope_rule": "REGION",
        "inputs_schema": {
            "ruling_id": {"type": "integer", "required": True},
            "returned_model_id": {"type": "integer", "required": True},
            "comments": {"type": "string", "required": False},
        },
        "conditions": {},
        "kardex_effect": "NONE",
        "is_bulk": True,
    },
    "confirm_na_return": {
        "code": "confirm_na_return",
        "entity": "CASE",
        "label": "Confirmar N/A Devolución",
        "from_stages": ["PENDIENTE_CONFIRMAR"],
        "to_stage": "SIN_DEVOLUCION",
        "permission": "review_definition_boss",
        "scope_rule": "REGION",
        "inputs_schema": {
            "comments": {"type": "string", "required": False},
        },
        "conditions": {},
        "kardex_effect": "NONE",
        "is_bulk": False,
    },
    "request_return_review": {
        "code": "request_return_review",
        "entity": "CASE",
        "label": "Solicitar Revisión de Devolución",
        "from_stages": ["PENDIENTE_CONFIRMAR"],
        "to_stage": "EN_REVISION",
        "permission": "confirm_return",
        "scope_rule": "REGION",
        "inputs_schema": {
            "review_reason": {"type": "string", "required": True},
        },
        "conditions": {},
        "kardex_effect": "NONE",
        "is_bulk": False,
    },
    "assign_repair_folio": {
        "code": "assign_repair_folio",
        "entity": "CASE",
        "label": "Asignar Folio de Reparación (Oficina)",
        "from_stages": ["CONFIRMADO"],
        "to_stage": "CONFIRMADO",
        "permission": "assign_repair_folio",
        "scope_rule": "GLOBAL",
        "inputs_schema": {
            "repair_folio": {"type": "string", "required": True},
            "folio_date": {"type": "date", "required": True},
            "insight_note_id": {"type": "integer", "required": False},
        },
        "conditions": {},
        "kardex_effect": "NONE",
        "is_bulk": False,
    },
    "assign_engineer": {
        "code": "assign_engineer",
        "entity": "CASE",
        "label": "Asignar Ingeniero para Reparación",
        "from_stages": ["CONFIRMADO"],
        "to_stage": "POR_REPARAR",
        "permission": "assign_engineer",
        "scope_rule": "REGION",
        "inputs_schema": {
            "assigned_engineer_id": {"type": "integer", "required": True},
        },
        "conditions": {},
        "kardex_effect": "NONE",
        "is_bulk": True,
    },
    "define_equipment": {
        "code": "define_equipment",
        "entity": "CASE",
        "label": "Definir Equipo Técnico",
        "from_stages": ["POR_REPARAR"],
        "to_stage": "DEFINIDO",
        "permission": "define_equipment",
        "scope_rule": "ASSIGNED",
        "inputs_schema": {
            "definition": {"type": "string", "required": True},  # REPARADO, HUESARIO, GARANTIA
            "repair_comments": {"type": "string", "required": True},
            "insight_repair_confirmed": {"type": "boolean", "required": False},
        },
        "conditions": {},
        "kardex_effect": "NONE",
        "is_bulk": False,
    },
    "boss_confirm_definition": {
        "code": "boss_confirm_definition",
        "entity": "CASE",
        "label": "Confirmar Definición Técnica (Jefe)",
        "from_stages": ["DEFINIDO"],
        "to_stage": "CONFIRMADO_JEFE",
        "permission": "review_definition_boss",
        "scope_rule": "REGION",
        "inputs_schema": {
            "comments": {"type": "string", "required": False},
        },
        "conditions": {},
        "kardex_effect": "NONE",
        "is_bulk": True,
    },
    "boss_reject_definition": {
        "code": "boss_reject_definition",
        "entity": "CASE",
        "label": "Rechazar Definición Técnica (Jefe)",
        "from_stages": ["DEFINIDO"],
        "to_stage": "POR_REPARAR",
        "permission": "review_definition_boss",
        "scope_rule": "REGION",
        "inputs_schema": {
            "comments": {"type": "string", "required": True},
        },
        "conditions": {},
        "kardex_effect": "NONE",
        "is_bulk": False,
    },
    "warehouse_confirm_definition": {
        "code": "warehouse_confirm_definition",
        "entity": "CASE",
        "label": "Confirmar Entrada a Almacén",
        "from_stages": ["CONFIRMADO_JEFE", "DEFINIDO"],
        "to_stage": "FINALIZADO",
        "permission": "review_definition_warehouse",
        "scope_rule": "REGION",
        "inputs_schema": {
            "destination_warehouse": {"type": "string", "required": True},
            "comments": {"type": "string", "required": False},
        },
        "conditions": {},
        "kardex_effect": "ENTRADA",
        "is_bulk": False,
    },
    "warehouse_reject_definition": {
        "code": "warehouse_reject_definition",
        "entity": "CASE",
        "label": "Rechazar Entrada a Almacén",
        "from_stages": ["CONFIRMADO_JEFE", "DEFINIDO"],
        "to_stage": "POR_REPARAR",
        "permission": "review_definition_warehouse",
        "scope_rule": "REGION",
        "inputs_schema": {
            "comments": {"type": "string", "required": True},
        },
        "conditions": {},
        "kardex_effect": "NONE",
        "is_bulk": False,
    },

    # =========================================================================
    # 3. HUESARIO, SCRAP, GARANTÍAS Y CANCELACIONES (FLUJO C)
    # =========================================================================
    "confirm_scrap_boss": {
        "code": "confirm_scrap_boss",
        "entity": "CASE",
        "label": "Confirmar Envío a Huesario (Jefe)",
        "from_stages": ["DEFINIDO", "CONFIRMADO_JEFE"],
        "to_stage": "HUESARIO_CONFIRMADO",
        "permission": "review_definition_boss",
        "scope_rule": "REGION",
        "inputs_schema": {
            "comments": {"type": "string", "required": False},
        },
        "conditions": {},
        "kardex_effect": "NONE",
        "is_bulk": True,
    },
    "deliver_scrap": {
        "code": "deliver_scrap",
        "entity": "CASE",
        "label": "Entregar a Huesario / Scrap Final",
        "from_stages": ["HUESARIO_CONFIRMADO", "DEFINIDO"],
        "to_stage": "FINALIZADO_HUESARIO",
        "permission": "manage_scrap",
        "scope_rule": "REGION",
        "inputs_schema": {
            "comments": {"type": "string", "required": False},
        },
        "conditions": {},
        "kardex_effect": "NONE",
        "is_bulk": False,
    },
    "return_scrap_to_repair": {
        "code": "return_scrap_to_repair",
        "entity": "CASE",
        "label": "Revertir Huesario a Reparación",
        "from_stages": ["HUESARIO_CONFIRMADO", "DEFINIDO"],
        "to_stage": "POR_REPARAR",
        "permission": "review_definition_boss",
        "scope_rule": "REGION",
        "inputs_schema": {
            "comments": {"type": "string", "required": True},
        },
        "conditions": {},
        "kardex_effect": "NONE",
        "is_bulk": False,
    },
    "set_warranty_solution": {
        "code": "set_warranty_solution",
        "entity": "CASE",
        "label": "Definir Solución de Garantía",
        "from_stages": ["DEFINIDO", "POR_REPARAR"],
        "to_stage": "DEFINIDO",
        "permission": "define_equipment",
        "scope_rule": "ASSIGNED",
        "inputs_schema": {
            "warranty_solution": {"type": "string", "required": True},  # NUEVO, RECUPERADO
            "new_serial": {"type": "string", "required": False},
            "comments": {"type": "string", "required": False},
        },
        "conditions": {},
        "kardex_effect": "NONE",
        "is_bulk": False,
    },
    "send_to_cellular_workshop": {
        "code": "send_to_cellular_workshop",
        "entity": "CASE",
        "label": "Enviar a Taller Celular (Garantía)",
        "from_stages": ["POR_REPARAR", "CONFIRMADO"],
        "to_stage": "ENVIADO_GARANTIA",
        "permission": "define_equipment",
        "scope_rule": "REGION",
        "inputs_schema": {
            "comments": {"type": "string", "required": True},
        },
        "conditions": {},
        "kardex_effect": "NONE",
        "is_bulk": False,
    },
    "cancel_return": {
        "code": "cancel_return",
        "entity": "CASE",
        "label": "Cancelar Devolución en Centro",
        "from_stages": ["PENDIENTE_CONFIRMAR"],
        "to_stage": "CANCELADA",
        "permission": "register_return",
        "scope_rule": "REGION",
        "inputs_schema": {
            "cancel_reason": {"type": "string", "required": True},
        },
        "conditions": {},
        "kardex_effect": "NONE",
        "is_bulk": False,
    },
    "manager_confirm_cancellation": {
        "code": "manager_confirm_cancellation",
        "entity": "CASE",
        "label": "Gerente Confirma Cancelación",
        "from_stages": ["CANCELADA"],
        "to_stage": "CANCELACION_CONFIRMADA",
        "permission": "authorize_voucher",
        "scope_rule": "ZONE",
        "inputs_schema": {
            "cancel_reason_id": {"type": "integer", "required": True},
            "comments": {"type": "string", "required": False},
        },
        "conditions": {},
        "kardex_effect": "NONE",
        "is_bulk": False,
    },
    "manager_reject_cancellation": {
        "code": "manager_reject_cancellation",
        "entity": "CASE",
        "label": "Gerente Rechaza Cancelación",
        "from_stages": ["CANCELADA"],
        "to_stage": "PENDIENTE_CONFIRMAR",
        "permission": "authorize_voucher",
        "scope_rule": "ZONE",
        "inputs_schema": {
            "comments": {"type": "string", "required": True},
        },
        "conditions": {},
        "kardex_effect": "NONE",
        "is_bulk": False,
    },
    "warehouse_receive_cancelled": {
        "code": "warehouse_receive_cancelled",
        "entity": "CASE",
        "label": "Almacén Recibe Cancelado",
        "from_stages": ["CANCELACION_CONFIRMADA", "CANCELADA"],
        "to_stage": "FINALIZADO_CANCELADO",
        "permission": "confirm_return",
        "scope_rule": "REGION",
        "inputs_schema": {
            "comments": {"type": "string", "required": False},
        },
        "conditions": {},
        "kardex_effect": "ENTRADA",
        "is_bulk": False,
    },
    "confirm_unused_equipment": {
        "code": "confirm_unused_equipment",
        "entity": "CASE",
        "label": "Confirmar Equipo No Utilizado",
        "from_stages": ["PENDIENTE_CONFIRMAR"],
        "to_stage": "CONFIRMADO",
        "permission": "review_definition_boss",
        "scope_rule": "REGION",
        "inputs_schema": {
            "comments": {"type": "string", "required": False},
        },
        "conditions": {},
        "kardex_effect": "NONE",
        "is_bulk": False,
    },
    "reject_unused_equipment": {
        "code": "reject_unused_equipment",
        "entity": "CASE",
        "label": "Rechazar Equipo No Utilizado",
        "from_stages": ["PENDIENTE_CONFIRMAR"],
        "to_stage": "SIN_DEVOLUCION",
        "permission": "review_definition_boss",
        "scope_rule": "REGION",
        "inputs_schema": {
            "comments": {"type": "string", "required": True},
        },
        "conditions": {},
        "kardex_effect": "NONE",
        "is_bulk": False,
    },

    # =========================================================================
    # 4. TALLER HABILITADO (FLUJO D - LOCATION: TALLER)
    # =========================================================================
    "send_to_workshop": {
        "code": "send_to_workshop",
        "entity": "CASE",
        "label": "Enviar a Taller Habilitado",
        "from_stages": ["CONFIRMADO", "PENDIENTE_CONFIRMAR"],
        "to_stage": "EN_TRANSITO_TALLER",
        "permission": "confirm_return",
        "scope_rule": "REGION",
        "inputs_schema": {
            "workshop_region_id": {"type": "integer", "required": True},
            "shipping_folio": {"type": "string", "required": False},
            "comments": {"type": "string", "required": False},
        },
        "conditions": {},
        "kardex_effect": "NONE",
        "is_bulk": False,
    },
    "cancel_workshop_send": {
        "code": "cancel_workshop_send",
        "entity": "CASE",
        "label": "Cancelar Envío a Taller Habilitado",
        "from_stages": ["EN_TRANSITO_TALLER"],
        "to_stage": "CONFIRMADO",
        "permission": "confirm_return",
        "scope_rule": "REGION",
        "inputs_schema": {
            "comments": {"type": "string", "required": False},
        },
        "conditions": {},
        "kardex_effect": "NONE",
        "is_bulk": False,
    },
    "workshop_confirm_entry": {
        "code": "workshop_confirm_entry",
        "entity": "CASE",
        "label": "Confirmar Recepción en Taller Habilitado",
        "from_stages": ["EN_TRANSITO_TALLER"],
        "to_stage": "EN_TALLER",
        "permission": "manage_workshop",
        "scope_rule": "REGION",
        "inputs_schema": {
            "returned_model_id": {"type": "integer", "required": False},
            "comments": {"type": "string", "required": False},
        },
        "conditions": {},
        "kardex_effect": "NONE",
        "is_bulk": False,
    },
    "workshop_request_review": {
        "code": "workshop_request_review",
        "entity": "CASE",
        "label": "Solicitar Revisión Técnica en Taller",
        "from_stages": ["EN_TALLER", "EN_TRANSITO_TALLER"],
        "to_stage": "EN_REVISION_TALLER",
        "permission": "manage_workshop",
        "scope_rule": "REGION",
        "inputs_schema": {
            "review_reason": {"type": "string", "required": True},
        },
        "conditions": {},
        "kardex_effect": "NONE",
        "is_bulk": False,
    },
    "workshop_assign_engineer": {
        "code": "workshop_assign_engineer",
        "entity": "CASE",
        "label": "Asignar Técnico de Taller",
        "from_stages": ["EN_TALLER", "CONFIRMADO", "EN_REVISION_TALLER"],
        "to_stage": "ASIGNADO",
        "permission": "assign_workshop_repair",
        "scope_rule": "REGION",
        "inputs_schema": {
            "assigned_engineer_id": {"type": "integer", "required": True},
        },
        "conditions": {},
        "kardex_effect": "NONE",
        "is_bulk": True,
    },
    "workshop_wait_parts": {
        "code": "workshop_wait_parts",
        "entity": "CASE",
        "label": "Poner en Espera de Refacción",
        "from_stages": ["EN_TALLER", "ASIGNADO", "POR_REPARAR"],
        "to_stage": "EN_ESPERA_REFACCION",
        "permission": "manage_workshop",
        "scope_rule": "REGION",
        "inputs_schema": {
            "comments": {"type": "string", "required": True},
        },
        "conditions": {},
        "kardex_effect": "NONE",
        "is_bulk": False,
    },
    "workshop_define_equipment": {
        "code": "workshop_define_equipment",
        "entity": "CASE",
        "label": "Definir Equipo en Taller Habilitado",
        "from_stages": ["ASIGNADO", "EN_ESPERA_REFACCION", "POR_REPARAR"],
        "to_stage": "DEFINIDO",
        "permission": "define_workshop_equipment",
        "scope_rule": "ASSIGNED",
        "inputs_schema": {
            "definition": {"type": "string", "required": True},  # REPARADO, HUESARIO, GARANTIA
            "repair_comments": {"type": "string", "required": True},
            "insight_repair_confirmed": {"type": "boolean", "required": False},
        },
        "conditions": {},
        "kardex_effect": "NONE",
        "is_bulk": False,
    },
    "workshop_confirm_definition": {
        "code": "workshop_confirm_definition",
        "entity": "CASE",
        "label": "Confirmar Definición en Taller (Jefe Taller)",
        "from_stages": ["DEFINIDO"],
        "to_stage": "CONFIRMADO_JEFE",
        "permission": "manage_workshop",
        "scope_rule": "REGION",
        "inputs_schema": {
            "comments": {"type": "string", "required": False},
        },
        "conditions": {},
        "kardex_effect": "NONE",
        "is_bulk": True,
    },
    "workshop_request_rereview": {
        "code": "workshop_request_rereview",
        "entity": "CASE",
        "label": "Rechazar / Solicitar Re-revisión en Taller",
        "from_stages": ["DEFINIDO"],
        "to_stage": "ASIGNADO",
        "permission": "manage_workshop",
        "scope_rule": "REGION",
        "inputs_schema": {
            "comments": {"type": "string", "required": True},
        },
        "conditions": {},
        "kardex_effect": "NONE",
        "is_bulk": False,
    },
    "workshop_warehouse_entry": {
        "code": "workshop_warehouse_entry",
        "entity": "CASE",
        "label": "Reingreso a Almacén desde Taller Habilitado",
        "from_stages": ["CONFIRMADO_JEFE", "DEFINIDO"],
        "to_stage": "FINALIZADO",
        "permission": "review_definition_warehouse",
        "scope_rule": "REGION",
        "inputs_schema": {
            "destination_warehouse": {"type": "string", "required": True},
            "comments": {"type": "string", "required": False},
        },
        "conditions": {},
        "kardex_effect": "ENTRADA",
        "is_bulk": False,
    },
}
