# Generated by Django 6.1.2 on 2026-10-07 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True, verbose_name='ID de AppSheet original')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('kind', models.CharField(choices=[('VALE_PDF', 'PDF de Vale de Salida'), ('REGRESO_PDF', 'PDF de Regreso / Caso'), ('FIRMA', 'Firma Digitalizada'), ('FOTO_TALLER', 'Foto / Evidencia de Taller'), ('QR', 'Código QR')], max_length=32, verbose_name='Tipo de documento')),
                ('related_type', models.CharField(db_index=True, max_length=64, verbose_name='Tipo de entidad relacionada')),
                ('related_id', models.BigIntegerField(db_index=True, verbose_name='ID de entidad relacionada')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='Archivo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'documents_document',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['related_type', 'related_id'], name='documents_d_related_4ff81e_idx'), models.Index(fields=['kind', 'created_at'], name='documents_d_kind_a057d2_idx')],
            },
        ),
    ]
