# Generated by Django 6.1.2 on 2026-10-07 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransitionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True, verbose_name='ID de AppSheet original')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Código único de transición')),
                ('label', models.CharField(max_length=128, verbose_name='Etiqueta / Nombre de acción')),
                ('entity', models.CharField(choices=[('VOUCHER', 'Vale'), ('LINE', 'Línea de Vale'), ('ITEM', 'Pieza de Inventario'), ('CASE', 'Caso de Equipo')], max_length=20, verbose_name='Entidad')),
                ('from_stages', models.JSONField(default=list, verbose_name='Etapas de origen permitidas')),
                ('to_stage', models.CharField(max_length=64, verbose_name='Etapa destino')),
                ('permission', models.CharField(max_length=64, verbose_name='Permiso requerido')),
                ('scope_rule', models.CharField(choices=[('REGION', 'Por Región del Usuario'), ('ZONE', 'Por Zona del Usuario'), ('OWN', 'Registros Propios del Usuario'), ('ASSIGNED', 'Registros Asignados al Usuario'), ('GLOBAL', 'Alcance Global')], default='REGION', max_length=20, verbose_name='Regla de alcance')),
                ('inputs_schema', models.JSONField(blank=True, default=dict, verbose_name='Esquema de campos de captura (JSON)')),
                ('conditions', models.JSONField(blank=True, default=dict, verbose_name='Condiciones de validación adicionales (JSON)')),
                ('kardex_effect', models.CharField(choices=[('NONE', 'Sin Efecto en Kárdex'), ('SALIDA', 'Movimiento de Salida'), ('ENTRADA', 'Movimiento de Entrada')], default='NONE', max_length=20, verbose_name='Efecto en Kárdex')),
                ('is_bulk', models.BooleanField(default=False, verbose_name='¿Permite ejecución en lote?')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Activa?')),
            ],
            options={
                'verbose_name': 'Regla de transición',
                'verbose_name_plural': 'Reglas de transición',
                'db_table': 'transitions_rule',
                'ordering': ['entity', 'code'],
            },
        ),
    ]
