# Generated by Django 6.1.2 on 2026-10-07 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True, verbose_name='ID de AppSheet original')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('movement_type', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=20, verbose_name='Tipo de movimiento')),
                ('serial_number', models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='Número de serie')),
                ('condition', models.CharField(choices=[('NUEVO', 'Nuevo'), ('RECUPERADO', 'Recuperado')], max_length=20, verbose_name='Condición')),
                ('warehouse', models.CharField(choices=[('STOCK', 'Stock'), ('PROYECTOS', 'Proyectos')], max_length=20, verbose_name='Almacén')),
                ('quantity', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('moved_at', models.DateTimeField(verbose_name='Fecha del movimiento')),
                ('transfer_folio', models.CharField(blank=True, default='', max_length=64, verbose_name='Folio de traspaso / referencia')),
                ('confirmed', models.BooleanField(default=True, verbose_name='¿Confirmado?')),
            ],
            options={
                'verbose_name': 'Movimiento de kárdex',
                'verbose_name_plural': 'Movimientos de kárdex',
                'db_table': 'inventory_movement',
                'ordering': ['-moved_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True, verbose_name='ID de AppSheet original')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del artículo')),
                ('brand', models.CharField(blank=True, default='', max_length=128, verbose_name='Marca')),
                ('model', models.CharField(blank=True, default='', max_length=128, verbose_name='Modelo')),
                ('is_inventoriable', models.BooleanField(default=True, help_text='Indica si requiere control de número de serie individual.', verbose_name='¿Es inventariable?')),
                ('category', models.ForeignKey(blank=True, limit_choices_to={'catalog': 'MATERIAL_CATEGORY'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_models', to='catalog.catalogvalue', verbose_name='Categoría de material')),
            ],
            options={
                'verbose_name': 'Modelo de equipo',
                'verbose_name_plural': 'Modelos de equipo',
                'db_table': 'inventory_equipment_model',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True, verbose_name='ID de AppSheet original')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('serial_number', models.CharField(db_index=True, max_length=128, verbose_name='Número de serie')),
                ('condition', models.CharField(choices=[('NUEVO', 'Nuevo'), ('RECUPERADO', 'Recuperado')], default='RECUPERADO', max_length=20, verbose_name='Condición')),
                ('warehouse', models.CharField(choices=[('STOCK', 'Stock'), ('PROYECTOS', 'Proyectos')], default='STOCK', max_length=20, verbose_name='Almacén')),
                ('quantity', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('insight_tag_confirmed', models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=10, null=True, verbose_name='Insight Tag confirmado')),
                ('dispatched_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de surtido')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cancelación')),
                ('cancel_note', models.TextField(blank=True, default='', verbose_name='Nota de cancelación')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_items', to=settings.AUTH_USER_MODEL, verbose_name='Cancelado por')),
                ('confirm_responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_items', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de confirmación')),
                ('equipment_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.equipmentmodel', verbose_name='Modelo de equipo')),
                ('insight_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_insight_notes', to='catalog.catalogvalue', verbose_name='Nota Insight')),
            ],
            options={
                'verbose_name': 'Pieza de inventario',
                'verbose_name_plural': 'Piezas de inventario',
                'db_table': 'inventory_item',
            },
        ),
    ]
