# Generated by Django 6.1.2 on 2026-10-07 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0002_initial'),
        ('inventory', '0001_initial'),
        ('org', '0001_initial'),
        ('vouchers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='vouchers.voucherline', verbose_name='Línea de vale'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='org.region', verbose_name='Región'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='vouchers.voucher', verbose_name='Vale de origen'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='cases.equipmentcase', verbose_name='Caso relacionado'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_movements', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='equipment_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.equipmentmodel', verbose_name='Modelo de equipo'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.inventoryitem', verbose_name='Pieza relacionada'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='org.region', verbose_name='Región'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['serial_number'], name='inventory_i_serial__71b54d_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['region', 'dispatched_at'], name='inventory_i_region__90ec6a_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['region', 'moved_at'], name='inventory_m_region__ab6b5e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['equipment_model', 'warehouse', 'condition'], name='inventory_m_equipme_0572dd_idx'),
        ),
    ]
