# Generated by Django 6.1.2 on 2026-10-07 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True, verbose_name='ID de AppSheet original')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('code', models.CharField(max_length=16, unique=True, verbose_name='Código de región')),
                ('name', models.CharField(max_length=128, verbose_name='Nombre de la región')),
                ('is_workshop', models.BooleanField(default=False, help_text='Indica si esta región opera como taller de reparación.', verbose_name='¿Es taller habilitado?')),
                ('workshop_name', models.CharField(blank=True, default='', max_length=128, verbose_name='Nombre del taller')),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
                'db_table': 'org_region',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True, verbose_name='ID de AppSheet original')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Nombre de la zona')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'db_table': 'org_zone',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True, verbose_name='ID de AppSheet original')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('number', models.IntegerField(unique=True, verbose_name='Número de centro')),
                ('name', models.CharField(max_length=128, verbose_name='Nombre del centro')),
                ('label', models.CharField(blank=True, default='', max_length=160, verbose_name='Etiqueta visible')),
                ('address', models.TextField(blank=True, default='', verbose_name='Dirección')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='centers', to='org.region', verbose_name='Región')),
            ],
            options={
                'verbose_name': 'Centro',
                'verbose_name_plural': 'Centros',
                'db_table': 'org_center',
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='region',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='org.zone', verbose_name='Zona'),
        ),
    ]
