# Generated by Django 6.1.2 on 2026-10-07 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True, verbose_name='ID de AppSheet original')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('catalog', models.CharField(db_index=True, max_length=64, verbose_name='Tipo de catálogo')),
                ('code', models.CharField(max_length=64, verbose_name='Código')),
                ('label', models.CharField(max_length=255, verbose_name='Etiqueta / Descripción')),
                ('sort', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Activo?')),
            ],
            options={
                'verbose_name': 'Valor de catálogo',
                'verbose_name_plural': 'Valores de catálogo',
                'db_table': 'catalog_value',
                'ordering': ['catalog', 'sort', 'label'],
                'constraints': [models.UniqueConstraint(fields=('catalog', 'code'), name='unique_catalog_code')],
            },
        ),
    ]
